name: check_syntax
#Gałąz na którą push aktywuje workflow
on:
  push:
    branches:
      - check_syntax
      

jobs:
  check_syntax:
    runs-on: ubuntu-latest
# Tworzę matrixa zawierającego dane wersje pythona
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
# workflow wykona testy na wersjach pythona określonych w matrixie
    steps:
    - name: Tworzenie pythona o określonej wersji
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
#wykonanie aktualizacji pip
    - name: aktualizacja pip
      run: python -m pip install --upgrade pip
# zainstalowanie biblioteki flake8
    - name: instalacja flake8
      run: | 
        python -m pip install flake8
        pip install --upgrade flake8

    - name: Wyświetlenie aktualnej wersji pythona
      run: |
        python --version
#Wykonanie analizy kodu
    - name: analiza stylu kodu przy użyciu biblioteki flake8
      run: flake8 
