name: check_syntax
#Wykona się przy push na main
on:
  push:
    branches:
      - main

jobs:
  check-syntax:
    runs-on: ${{ matrix.os }}
# wesje pythona oraz OS z wylaczeniem wersji 3.10 na ubuntu
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [windows-latest, ubuntu-latest]
        exclude:
        - python-version: "3.10"
          os: ubuntu-latest
    
    steps:
    - name: Utworzenie programu pythona
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
     

    - name: Aktualizacja pip
      run: |
        python -m pip install --upgrade pip
#Instalacja potrzebnych bibliotek, unittest jest załączony domyślnie z pythonem
    - name: Instalacja flake8
      run: |
        python -m pip install flake8
#Wyświetla się aktualna wersja pythona
    - name: Wyświetlenie aktualnej wersji pythona
      run: python --version
#Uruchomienie flake8
    - name: Run flake8
      run: |
        flake8 
