name: Check Syntax

on:
  push:
    branches:
      - main

jobs:
  check-syntax:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        exclude-versions: ${{ matrix.python-version == '3.10' && startsWith(runner.os, 'ubuntu') }}

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install flake8 and unittest
      run: |
        python -m pip install flake8

    - name: Display Python version
      run: |
        python --version

    - name: Run flake8
      run: |
        flake8

    - name: Run unittest
      run: |
        python -m unittest discover
